# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
supi: 'imsi-208950000000031'
# Mobile Country Code value of HPLMN
mcc: '208'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '95'

# Permanent subscription key
key: '0C0A34601D4F07677303652C0462535B'
# Operator code (OP or OPC) of the UE
op: '63bfa50ee6523365ff14c1f45f88737d'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 192.168.70.141

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'default'
    slice:
      sst: 222
      sd: 123 #0x00007b #5e , dans la BD, sd est marqué en string "123" alors quici , c'est la valeur 123 en Hexa

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 222
    sd: 123 # 0x00007b #6e 

# Default Configured NSSAI for this UE
default-nssai:
  - sst: 222
    sd: 123 #0x00007b #7e modificationdu 

# Supported integrity algorithms by this UE
integrity:
  IA0: true #premiere modif, l'amf demande IA0 comme algo de securité
  IA1: true
  IA2: true
  IA3: true

# Supported encryption algorithms by this UE
ciphering: #cette section configure les algo de securité autorisé
#il n'y a pas A0 qui equivaut à pas vraiment de securité, on va le rajouter 
  EA0: true #2e modificarion
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
